#ifndef WINDOWS_LANGUAGE_IDS_H
#define WINDOWS_LANGUAGE_IDS_H

#include <string>
#include <vector>
#include <cstdint>
#include "internals/InternalTypes.h"

namespace OpenType {

struct WindowsLanguageID {
    std::string primary_language;
    std::string region;
    OT_UINT32 id;
};


std::ostream& operator<<( std::ostream& out, const WindowsLanguageID id );


const std::vector<WindowsLanguageID> windows_language_ids = {
        {"Afrikaans", "South Africa", 0x0436 },
        {"Albanian","Albania",0x041C},
        {"Alsatian","France",0x484},
        {"Amharic","Ethiopia",0x045E},
        {"Arabic","Algeria",0x1401},
        {"Arabic","Bahrain",0x3C01},
        {"Arabic","Egypt",0x0C01},
        {"Arabic","Iraq",0x801},
        {"Arabic","Jordan",0x2C01},
        {"Arabic","Kuwait",0x3401},
        {"Arabic","Lebanon",0x3001},
        {"Arabic","Libya",0x1001},
        {"Arabic","Morocco",0x1801},
        {"Arabic","Oman",0x2001},
        {"Arabic","Qatar",0x4001},
        {"Arabic","Saudi Arabia",0x401},
        {"Arabic","Syria",0x2801},
        {"Arabic","Tunisia",0x1C01},
        {"Arabic","U.A.E.",0x3801},
        {"Arabic","Yemen",0x2401},
        {"Armenian","Armenia",0x042B},
        {"Assamese","India",0x044D},
        {"Azeri (Cyrillic)","Azerbaijan",0x082C},
        {"Azeri (Latin)","Azerbaijan",0x042C},
        {"Bashkir","Russia",0x046D},
        {"Basque","Basque",0x042D},
        {"Belarusian","Belarus",0x423},
        {"Bengali","Bangladesh",0x845},
        {"Bengali","India",0x445},
        {"Bosnian (Cyrillic)","Bosnia and Herzegovina",0x201A},
        {"Bosnian (Latin)","Bosnia and Herzegovina",0x141A},
        {"Breton","France",0x047E},
        {"Bulgarian","Bulgaria",0x402},
        {"Catalan","Catalan",0x403},
        {"Chinese","Hong Kong S.A.R.",0x0C04},
        {"Chinese","Macao S.A.R.",0x1404},
        {"Chinese","People’s Republic of China",0x804},
        {"Chinese","Singapore",0x1004},
        {"Chinese","Taiwan",0x404},
        {"Corsican","France",0x483},
        {"Croatian","Croatia",0x041A},
        {"Croatian (Latin)","Bosnia and Herzegovina",0x101A},
        {"Czech","Czech Republic",0x405},
        {"Danish","Denmark",0x406},
        {"Dari","Afghanistan",0x048C},
        {"Divehi","Maldives",0x465},
        {"Dutch","Belgium",0x813},
        {"Dutch","Netherlands",0x413},
        {"English","Australia",0x0C09},
        {"English","Belize",0x2809},
        {"English","Canada",0x1009},
        {"English","Caribbean",0x2409},
        {"English","India",0x4009},
        {"English","Ireland",0x1809},
        {"English","Jamaica",0x2009},
        {"English","Malaysia",0x4409},
        {"English","New Zealand",0x1409},
        {"English","Republic of the Philippines",0x3409},
        {"English","Singapore",0x4809},
        {"English","South Africa",0x1C09},
        {"English","Trinidad and Tobago",0x2C09},
        {"English","United Kingdom",0x809},
        {"English","United States",0x409},
        {"English","Zimbabwe",0x3009},
        {"Estonian","Estonia",0x425},
        {"Faroese","Faroe Islands",0x438},
        {"Filipino","Philippines",0x464},
        {"Finnish","Finland",0x040B},
        {"French","Belgium",0x080C},
        {"French","Canada",0x0C0C},
        {"French","France",0x040C},
        {"French","Luxembourg",0x140c},
        {"French","Principality of Monaco",0x180C},
        {"French","Switzerland",0x100C},
        {"Frisian","Netherlands",0x462},
        {"Galician","Galician",0x456},
        {"Georgian","Georgia",0x437},
        {"German","Austria",0x0C07},
        {"German","Germany",0x407},
        {"German","Liechtenstein",0x1407},
        {"German","Luxembourg",0x1007},
        {"German","Switzerland",0x807},
        {"Greek","Greece",0x408},
        {"Greenlandic","Greenland",0x046F},
        {"Gujarati","India",0x447},
        {"Hausa (Latin)","Nigeria",0x468},
        {"Hebrew","Israel",0x040D},
        {"Hindi","India",0x439},
        {"Hungarian","Hungary",0x040E},
        {"Icelandic","Iceland",0x040F},
        {"Igbo","Nigeria",0x470},
        {"Indonesian","Indonesia",0x421},
        {"Inuktitut","Canada",0x045D},
        {"Inuktitut (Latin)","Canada",0x085D},
        {"Irish","Ireland",0x083C},
        {"isiXhosa","South Africa",0x434},
        {"isiZulu","South Africa",0x435},
        {"Italian","Italy",0x410},
        {"Italian","Switzerland",0x810},
        {"Japanese","Japan",0x411},
        {"Kannada","India",0x044B},
        {"Kazakh","Kazakhstan",0x043F},
        {"Khmer","Cambodia",0x453},
        {"K’iche","Guatemala",0x486},
        {"Kinyarwanda","Rwanda",0x487},
        {"Kiswahili","Kenya",0x441},
        {"Konkani","India",0x457},
        {"Korean","Korea",0x412},
        {"Kyrgyz","Kyrgyzstan",0x440},
        {"Lao","Lao P.D.R.",0x454},
        {"Latvian","Latvia",0x426},
        {"Lithuanian","Lithuania",0x427},
        {"Lower Sorbian","Germany",0x082E},
        {"Luxembourgish","Luxembourg",0x046E},
        {"Macedonian (FYROM)","Former Yugoslav Republic of Macedonia",0x042F},
        {"Malay","Brunei Darussalam",0x083E},
        {"Malay","Malaysia",0x043E},
        {"Malayalam","India",0x044C},
        {"Maltese","Malta",0x043A},
        {"Maori","New Zealand",0x481},
        {"Mapudungun","Chile",0x047A},
        {"Marathi","India",0x044E},
        {"Mohawk","Mohawk",0x047C},
        {"Mongolian (Cyrillic)","Mongolia",0x450},
        {"Mongolian (Traditional)","People’s Republic of China",0x850},
        {"Nepali","Nepal",0x461},
        {"Norwegian (Bokmal)","Norway",0x414},
        {"Norwegian (Nynorsk)","Norway",0x814},
        {"Occitan","France",0x482},
        {"Odia (formerly Oriya)","India",0x448},
        {"Pashto","Afghanistan",0x463},
        {"Polish","Poland",0x415},
        {"Portuguese","Brazil",0x416},
        {"Portuguese","Portugal",0x816},
        {"Punjabi","India",0x446},
        {"Quechua","Bolivia",0x046B},
        {"Quechua","Ecuador",0x086B},
        {"Quechua","Peru",0x0C6B},
        {"Romanian","Romania",0x418},
        {"Romansh","Switzerland",0x417},
        {"Russian","Russia",0x419},
        {"Sami (Inari)","Finland",0x243B},
        {"Sami (Lule)","Norway",0x103B},
        {"Sami (Lule)","Sweden",0x143B},
        {"Sami (Northern)","Finland",0x0C3B},
        {"Sami (Northern)","Norway",0x043B},
        {"Sami (Northern)","Sweden",0x083B},
        {"Sami (Skolt)","Finland",0x203B},
        {"Sami (Southern)","Norway",0x183B},
        {"Sami (Southern)","Sweden",0x1C3B},
        {"Sanskrit","India",0x044F},
        {"Serbian (Cyrillic)","Bosnia and Herzegovina",0x1C1A},
        {"Serbian (Cyrillic)","Serbia",0x0C1A},
        {"Serbian (Latin)","Bosnia and Herzegovina",0x181A},
        {"Serbian (Latin)","Serbia",0x081A},
        {"Sesotho sa Leboa","South Africa",0x046C},
        {"Setswana","South Africa",0x432},
        {"Sinhala","Sri Lanka",0x045B},
        {"Slovak","Slovakia",0x041B},
        {"Slovenian","Slovenia",0x424},
        {"Spanish","Argentina",0x2C0A},
        {"Spanish","Bolivia",0x400A},
        {"Spanish","Chile",0x340A},
        {"Spanish","Colombia",0x240A},
        {"Spanish","Costa Rica",0x140A},
        {"Spanish","Dominican Republic",0x1C0A},
        {"Spanish","Ecuador",0x300A},
        {"Spanish","El Salvador",0x440A},
        {"Spanish","Guatemala",0x100A},
        {"Spanish","Honduras",0x480A},
        {"Spanish","Mexico",0x080A},
        {"Spanish","Nicaragua",0x4C0A},
        {"Spanish","Panama",0x180A},
        {"Spanish","Paraguay",0x3C0A},
        {"Spanish","Peru",0x280A},
        {"Spanish","Puerto Rico",0x500A},
        {"Spanish (Modern Sort)","Spain",0x0C0A},
        {"Spanish (Traditional Sort)","Spain",0x040A},
        {"Spanish","United States",0x540A},
        {"Spanish","Uruguay",0x380A},
        {"Spanish","Venezuela",0x200A},
        {"Sweden","Finland",0x081D},
        {"Swedish","Sweden",0x041D},
        {"Syriac","Syria",0x045A},
        {"Tajik (Cyrillic)","Tajikistan",0x428},
        {"Tamazight (Latin)","Algeria",0x085F},
        {"Tamil","India",0x449},
        {"Tatar","Russia",0x444},
        {"Telugu","India",0x044A},
        {"Thai","Thailand",0x041E},
        {"Tibetan","PRC",0x451},
        {"Turkish","Turkey",0x041F},
        {"Turkmen","Turkmenistan",0x442},
        {"Uighur","PRC",0x480},
        {"Ukrainian","Ukraine",0x422},
        {"Upper Sorbian","Germany",0x042E},
        {"Urdu","Islamic Republic of Pakistan",0x420},
        {"Uzbek (Cyrillic)","Uzbekistan",0x843},
        {"Uzbek (Latin)","Uzbekistan",0x443},
        {"Vietnamese","Vietnam",0x042A},
        {"Welsh","United Kingdom",0x452},
        {"Wolof","Senegal",0x488},
        {"Yakut","Russia",0x485},
        {"Yi","PRC",0x478},
        {"Yoruba","Nigeria",0x046A}
};

}

#endif // WINDOWS_LANGUAGE_IDS_H
